### PR TITLE
Update Zone to 0.8.18 and export jasmine/mocha testing scripts

### PR DESCRIPTION
**Pull request by justindujardin**
It's hard to include the jasmine/mocha specific zone patches because they depend on ordering. While building a custom {N} entry point, also build single file includes for all the jasmine/mocha zone extensions that are needed to support TestBed.

### CODE REVIEW

**Comment by justindujardin** [comment]
This is the relevant commit: https://github.com/NativeScript/zone.js/pull/1/commits/f7f3183b964171d66283150d2004cc342085b5a6

**Comment by hypery2k** [comment]
@mhevery or @alxhub Are we going to see this PR merged?

**Comment by vakrilov** [comment]
Hey @justindujardin - can you create target the `zone-nativescript` in this PR and rebase the branch onto it.

**Comment by justindujardin** [comment]
@vakrilov it was a pain to rebase the update of Zone.js so I just opened a new PR that only applies the exported testing changes. If you need the updated version of Zone, let me know: https://github.com/NativeScript/zone.js/pull/2

**Pull request closed without merging**
